version: '3'
services:
  pgdb:
    image: "postgres:11"
    container_name: "pgdb"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
    ports:
      - "54320:5432"
    volumes:
      - pgdb:/var/lib/pgdb

volumes:
  pgdb: